import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Serif_4, Caveat } from "next/font/google";
import "./globals.css";
import { cookies, headers } from 'next/headers'
import { defaultLocale } from '@/lib/locales' 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-serif",
  weight: ["300","400","600","700"],
  subsets: ["latin"],
  display: 'swap',
});

const caveat = Caveat({
  variable: "--font-caveat",
  weight: ["400","700"],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'),
};

import DevPerfProtector from '@/components/dev/DevPerfProtector'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let locale = defaultLocale

  try {
    const cookieStore = await cookies()
    const cookieLocale = cookieStore.get('locale')?.value
    if (cookieLocale === "fr" || cookieLocale === "en") {
      locale = cookieLocale
    } else {
      locale = defaultLocale
    }
  } catch {
    // Fallback: parse header cookie string if cookies() is unavailable
    try {
      const cookieHeader = (await headers()).get('cookie') ?? ''
      const match = cookieHeader.match(/(?:^|; )locale=([^;]+)/)
      const parsedLocale = match ? decodeURIComponent(match[1]) : defaultLocale;
      locale = (parsedLocale === "fr" || parsedLocale === "en") ? parsedLocale : defaultLocale;
    } catch {
      locale = defaultLocale
    }
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sourceSerif.variable} ${caveat.variable} antialiased`}
      >
        {/* Dev-only protective wrapper to avoid dev tooling throwing on performance.measure */}
        <DevPerfProtector />
        {children}
      </body>
    </html>
  );
}
